# This is a basic workflow to help you get started with Actions

name: CI1


on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: curl before
        run: |
          curl -4 ip.sb || echo "IPv4 not available"
          curl -6 ip.sb || echo "IPv6 not available"

      - name: Use local WARP composite action
        uses: ./
        with:
          stack: ipv6

      - name: curl after
        run: |
          curl -4 ip.sb || echo "IPv4 not available"
          curl -6 ip.sb || echo "IPv6 not available"
