name: ipv6test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          curl -4 ip.sb || echo "IPv4 not available"
          run: curl -6 ip.sb || echo "IPv6 not available"

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
          mode: client    # Optional. Support [ wireguard, client ]. Default is wireguard.
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -4 ip.sb || echo "IPv4 not available"
          run: curl -6 ip.sb || echo "IPv6 not available"
          echo Add other actions to build,
          echo test, and deploy your project.
